version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull grafana/k6 image...
      - docker pull grafana/k6 || exit 1
  build:
    commands:
      - echo Run performance test
      - docker run -i grafana/k6 run - <scripts/cloud_stress_teste_search.js || exit 1
  post_build:
    commands:
      - echo Performance test complete
